### ISSUE TITLE
Update packages (lodash has a high vulnerability)

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/common-nodejs-utils#14]
| bcgov/common-nodejs-utils
-- | --
Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json.package-lock.json update suggested: lodash ~> 4.17.13. | Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json. | package-lock.json update suggested: lodash ~> 4.17.13.
Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json.
package-lock.json update suggested: lodash ~> 4.17.13.

**Comment by jleach** [comment]
All packages updated. Closing.
